# Generated by Django 2.1.10 on 2020-05-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='email')),
                ('telefone', models.IntegerField(verbose_name='telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('data', models.CharField(max_length=21, verbose_name='data')),
                ('imagem', models.CharField(max_length=150, verbose_name='imagem')),
                ('conteudo', models.CharField(max_length=800, verbose_name='conteudo')),
                ('autor', models.CharField(max_length=50, verbose_name='autor')),
            ],
        ),
    ]
