# Generated by Django 2.1.10 on 2020-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.CharField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='telefone'),
        ),
    ]
