# Generated by Django 2.1.10 on 2020-05-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200512_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='conteudo',
            field=models.TextField(verbose_name='conteudo'),
        ),
        migrations.AlterField(
            model_name='tutoriais',
            name='data',
            field=models.DateTimeField(max_length=21, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='tutoriais',
            name='imagem',
            field=models.ImageField(max_length=150, upload_to='', verbose_name='imagem'),
        ),
    ]
