# Generated by Django 2.1.10 on 2020-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200512_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='data',
            field=models.DateTimeField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='tutoriais',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='tutoriais',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='tutoriais',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='titulo'),
        ),
    ]
