# Generated by Django 2.1.10 on 2020-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200512_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoriais',
            name='imagem',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
